name: Releases

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    name: Create new release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21
        with:
          elixir-version: "1.15.7-otp-26"
          otp-version: "26.1.2"

      - name: Install dependencies
        run: mix deps.get

      - name: Create Obsidian files
        run: mix convert

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "priv/sources/Siomenuv_archiv_v*.xlsx,priv/asterion.zip"
